TestTask/Controllers/LikeController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TestTask.Services;

namespace TestTask.Controllers
{
    [Route("[controller]")]
    public class LikeController : Controller
    {
        private ILogger logger;
        private PageService service;
        public LikeController(PageService service, ILogger<LikeController> logger)
        {
            this.service = service;
            this.logger = logger;
        }

        [Authorize]
        [HttpGet]
        [Route("LikePage/{pageName}")]
        public async Task<IActionResult> LikePage(string pageName)
        {
            logger.LogInformation($"Executing LikePage/{pageName}");
            int likes = await service.LikePage(pageName, User.Identity.Name, 1);
            return Ok(likes);
        }

        [Authorize]
        [HttpGet]
        [Route("DisLikePage/{pageName}")]
        public async Task<IActionResult> DisLikePage(string pageName)
        {
            logger.LogInformation($"Executing DisLikePage/{pageName}");
            int likes = await service.LikePage(pageName, User.Identity.Name, -1);
            return Ok(likes);
        }
    }
}

TestTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestTask</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">TestTask</a>
            </div>
			
				 <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
					@if (!(bool)ViewData["IsLoggedIn"]) 
					{
						<li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
					}
					@if ((bool)ViewData["IsLoggedIn"]) 
					{
						<li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
					}
                </ul>
            </div>
			
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
		@{
		var isLike = true;
		}
        <footer>
            <p>&copy; 2019 - TestTask</p>
			<div class="form-group">
			<p id= "TotalLikesAmount">Total likes: @ViewData["TotalLikes"]</p>
			@if ((bool)ViewData["IsLoggedIn"]) 
			{	
				@if((bool)ViewData["IsLiked"])
				{
					<button onclick="LikePage()" id="LikeButton">Dislike it</button>
				} else {
					<button onclick="LikePage()" id="LikeButton">Like it</button>
				}
			}
			</div>
        </footer>
    </div>

	<script>
	function LikePage(){
		if($("#LikeButton").text() == "Like it") {
			plusOneLike();
			return;
		}
		minusOneLike();
	}

	function plusOneLike(){
		$.get( "@Url.Action("LikePage", "Like")/@ViewData["Title"]", 
				function( data ) {
					ReloadData("Dislike it", data);
				});
	}

	function minusOneLike(){
	$.get( "@Url.Action("DisLikePage", "Like")/@ViewData["Title"]", 
			function( data ) {
				ReloadData("Like it", data);
			});
	}

	function ReloadData(text, data){
		$("#TotalLikesAmount").text(`Total likes ${data}`);
		$("#LikeButton").text(text);
	}
	</script>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>